[package]
name = "tempura_render"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.37.2"
ash-window = "0.12.0"
raw-window-handle = "0.5"
tempura_graphics = { version = "0.1.0", path = "../tempura_graphics" }
