[package]
name = "tempura_vulkan_render"
version = "0.1.0"
edition = "2021"

[features]
debug = []
develop = []

[dependencies]
ash = "0.37"
ash-window = "0.12"
derive_builder = "0.12"
raw-window-handle = "0.5"
spirv-reflect = "0.2.3"
tempura_render = { path = "../tempura_render" }
