[package]
name = "tmp_vk_renderer_old"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.37"
ash-window = "0.12.0"
raw-window-handle = "0.5"
vk-mem = { git = "https://github.com/gwihlidal/vk-mem-rs", branch = "master"}
